export const productsdata = [
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirt",
    name: "T-Shirt",
    category: "Men",
    featured: true,
    productImage:
      "https://images.meesho.com/images/products/438484702/93x2j_400.webp",
    title:
      "Life Line D Full Sleeve Tshirt for Boys and men White full sleeve tshirt",
    description:
      "High Quality Fabric: 62% cotton + 35% polyester fiber + 3% spandex.The long sleeve shirt is made of stretch fabric,makes you move body easier;soft and comfortable with good breathability.",
    price: 1299,
    color: "White",
    countInStock: 110,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirt",
    name: "T-Shirt",
    category: "Men",
    featured: true,
    productImage:
      "https://images.meesho.com/images/products/400584487/osekr_512.webp",
    title: "AOOSH Men's Engineered Stripes Regular Polo Midnight Navy Tshirts",
    description:
      "Inakz Western Wear Men fashion Suitable for All season men and boys attitude Tshirt comfy Men and Boys Round Neck Printed Cotton Blend Blend Full Sleeve Black Korean Style Trending T-Shirt best cloth for season Best Gift for a Man.",
    price: 3999,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirt",
    name: "T-Shirt",
    category: "Men",
    productImage:
      "https://images.meesho.com/images/products/281344188/xnskn_400.webp",
    title: "AOOSH Men's Solid Regular Mandarin Yellow Tshirts",
    description:
      "Inakz Western Wear Men fashion Suitable for All season men and boys attitude Tshirt comfy Men and Boys Round Neck Printed Cotton Blend Blend Full Sleeve Black Korean Style Trending T-Shirt best cloth for season Best Gift for a Man.",
    price: 4999,
    color: "Yellow",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirt",
    name: "T-Shirt",
    category: "Men",
    productImage:
      "https://images.meesho.com/images/products/279598835/sre4p_400.webp",
    title: "AOOSH Men's Solid Regular Mandarin Yellow Tshirts",
    description:
      "Inakz Western Wear Men fashion Suitable for All season men and boys attitude Tshirt comfy Men and Boys Round Neck Printed Cotton Blend Blend Full Sleeve Black Korean Style Trending T-Shirt best cloth for season Best Gift for a Man.",
    price: 4299,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirt",
    name: "T-Shirt",
    category: "Men",
    productImage:
      "https://images.meesho.com/images/products/421270295/3wtwb_400.webp",
    title: "AOOSH Men's Solid Regular Mandarin Yellow Tshirts",
    description:
      "Inakz Western Wear Men fashion Suitable for All season men and boys attitude Tshirt comfy Men and Boys Round Neck Printed Cotton Blend Blend Full Sleeve Black Korean Style Trending T-Shirt best cloth for season Best Gift for a Man.",
    price: 5299,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirt",
    name: "T-Shirt",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/102346967/5jdw7_400.webp",
    title:
      "Casual Polyester Blend V-Neck Full Sleeves Black Crop Top (17 ' Inches)",
    description:
      "Inakz Western Wear Men fashion Suitable for All season men and boys attitude Tshirt comfy Men and Boys Round Neck Printed Cotton Blend Blend Full Sleeve Black Korean Style Trending T-Shirt best cloth for season Best Gift for a Man.",
    price: 4999,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/438736059/cyx7a_512.webp",
    title: "Casual Full Sleeves Black Crop Top",
    description:
      "Inakz Western Wear Men fashion Suitable for All season men and boys attitude Tshirt comfy Men and Boys Round Neck Printed Cotton Blend Blend Full Sleeve Black Korean Style Trending T-Shirt best cloth for season Best Gift for a Man.",
    price: 4999,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/318255252/bjofn_512.webp",
    title: "KNIT KRAFT IMPEX Sleeveless Casual Striped Crop Top (18'Inches)",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish. Made in India Product for the Indian market at the Best Prices..Our Purpose Is To Boost enhancing you stylish and fashion look.Popular styles include Hoodie. Become Your Stylish Wardrob. We hopes everyone can find their own unique.This cotton Blend makes the perfect season-spanning layer, for a cool morning run, atop a tee with your jeans, even on the beach. Keeping it in your gym bag, your car, or take it along in your weekend tote where its versatility will serve you well.",
    price: 2999,
    color: "Yellow",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/394407803/eyh63_400.webp",
    title: "Comfy Fashionable Women Top & Tunics",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish. Made in India Product for the Indian market at the Best Prices..Our Purpose Is To Boost enhancing you stylish and fashion look.Popular styles include Hoodie. Become Your Stylish Wardrob. We hopes everyone can find their own unique.This cotton Blend makes the perfect season-spanning layer, for a cool morning run, atop a tee with your jeans, even on the beach. Keeping it in your gym bag, your car, or take it along in your weekend tote where its versatility will serve you well.",
    price: 2999,
    color: "Yellow",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/386362568/3tdiv_512.webp",
    title: "womens printed balloon sleeve top",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish.",
    price: 3999,
    color: "Red",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/237015727/oywih_512.webp",
    title: "Blue Print Mandarin Collar Empire pure cotton A-Line top",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish.",
    price: 3999,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/147286866/wc0xt_512.webp",
    title: "Blue Print Mandarin Collar Empire pure cotton A-Line top",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish.",
    price: 3999,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/162029361/qmy9m_512.webp",
    title: "JIYA Women's Rayon Printed Stylish Top",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish.",
    price: 3999,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/44004561/grh8d_512.webp",
    title: "JIYA Women's Rayon Printed Stylish Top",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish.",
    price: 2999,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://images.meesho.com/images/products/83092761/khsdt_400.webp",
    title: "JIYA Women's Rayon Printed Stylish Top",
    description:
      "KNIT KRAFT IMPEXpresent their collection of top With great comfort and style. This top will upgrade your wardrobe collection as well as your look.Try something new that's perfect for the trend that you are going to flaunt as you wear this top. Its Design is the best part which makes it more than normal outwear, this top will not fail to catch your fancy at a single glance. This Summer Indian homegrown brings you the best quality cotton SleeveLESS T-Shirts to keep you Stylish.",
    price: 2999,
    color: "Red",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://m.media-amazon.com/images/I/71qghgds8aL._AC_UL320_.jpg",
    title: "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 2999,
    color: "Red",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Sleeves",
    name: "Sleeves",
    category: "Women",
    productImage:
      "https://m.media-amazon.com/images/I/71HmppFhPpL._AC_SY500_.jpg",
    title: "AUTOMET Long Sleeve Shirts for Women Lace V Neck Basic Casual Tops",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1999,
    color: "Red",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirts",
    name: "T-Shirts",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/61OUbo3BNrL._AC_SX522_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 999,
    color: "White",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirts",
    name: "T-Shirts",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/71D9FNDeMCL._AC_SY500_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 999,
    color: "Yellow",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirts",
    name: "T-Shirts",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/31LoVDswz7L._AC_UF480,600_SR480,600_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1199,
    color: "Yellow",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "T-Shirts",
    name: "T-Shirts",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/81jxvHU8z2L._AC_SX522_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1499,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/71eafi+NGAL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 999,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/61byrE4bPCL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 999,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/71W0cQLP37L._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 999,
    color: "White",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/617cU+55HtL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 899,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Shirts",
    name: "Shirts",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/71O-xvXBC4L._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 999,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Shirts",
    name: "Shirts",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/61ldVm51bNL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 799,
    color: "White",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Top",
    sizes: ["S", "M", "L"],
    type: "Shirts",
    name: "Shirts",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/51FiVTJDUHL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 799,
    color: "White",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/51DvzL+D6hL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1199,
    color: "White",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Kids",
    productImage:
      "https://m.media-amazon.com/images/I/71W7GRc8YPL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1199,
    color: "Gray",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Men",
    productImage:
      "https://m.media-amazon.com/images/I/51Crt9Ro1sL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1199,
    color: "Black",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Men",
    productImage:
      "https://m.media-amazon.com/images/I/61ocQfqNIDL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1199,
    color: "Blue",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Men",
    productImage:
      "https://m.media-amazon.com/images/I/71De-IPZoeL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1599,
    color: "Gray",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Women",
    productImage:
      "https://m.media-amazon.com/images/I/61YfQT073ML._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1999,
    color: "Gray",
    countInStock: 120,
  },
  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Women",
    productImage:
      "https://m.media-amazon.com/images/I/51Xf5E+muQL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1799,
    color: "Black",
    countInStock: 120,
  },

  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Women",
    productImage:
      "https://m.media-amazon.com/images/I/61TqeemL7pL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1799,
    color: "Black",
    countInStock: 120,
  },

  {
    userId: "66de079146031a83112989ac",
    subCategory: "Bottom",
    sizes: ["S", "M", "L"],
    type: "Pents",
    name: "Pents",
    category: "Women",
    productImage:
      "https://m.media-amazon.com/images/I/71gKcqlFfnL._AC_UL320_.jpg",
    title: "Gildan Youth Ultra Cotton T-Shirt, Style G2000B, Multipack",
    description:
      "AUTOMET Womens Long Sleeve Shirts Fall Outfits Casual Tops Basic Crewneck Tees Loose Fitted Fashion Comfy Winter Clothes 2024.",
    price: 1799,
    color: "Blue",
    countInStock: 120,
  },
];
